server:
  port:   ${PORT:8080}
# DATABASE-hkdev, 아래쪽은 local, local로 테스트 하고 dev로 갈 예정 -> prod


spring:
  freemarker:
    cache: false
  thymeleaf:
    prefix: file:src/main/resources/templates/
    #      classpath:
    suffix: .html
    check-template-location: true
    mode: HTML5
    encoding: UTF-8
    cache: false

  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/hksbdemo
#    username: postgres
#    password: 1234
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
#    url: jdbc:postgresql://ec2-23-20-140-229.compute-1.amazonaws.com:5432/d9a6b8pktcch8d
#    username: grettxkdredndq
#    password: 9ec77fc50c273ec801eb7f8a923305537e672279e94b7aa9a521344e24fbbf9e
  sql:
    init:
      encoding: utf-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

