server:
  port:   ${PORT:8080}

spring:
  freemarker:
    cache: false
  thymeleaf:
    prefix: file:src/main/resources/templates/
    #      classpath:
    suffix: .html
    check-template-location: true
    mode: HTML5
    encoding: UTF-8
    cache: false
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
#    localhost:8080
#    url: jdbc:postgresql://localhost:5432/hksbdemo
#    username: postgres
#    password: 1234
#    heroku 배포
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  sql:
    init:
      encoding: utf-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: validate
#      ddl: 엔터티 기준, 테이블 생성규칙 정의
#      개발환경: update / 운영환경: none or validate(변경사항이 있는지 검사만)로 정의함.

